### ISSUE TITLE
サーバー側プログラムLaravelフレームワークで作成

### ISSUE THREAD

**Issue by yoshikichi** [piot-jp-Team/ghf_sensorhousing#2]
上限値と下限値を超えたときのアラートメール機能を追加する予定です。センサー設定には上限値と下限値がすでにありますが、５分間隔でCRONでスケジュールし発報する予定です。発報インターバルはシステム設定に入れる予定です。

**Comment by mocotech** [comment]
試し書込み

**Comment by yoshikichi** [comment]
ghf_webappリポジトリに移動しました。
